### ISSUE TITLE
problemi MongoDB

### ISSUE THREAD

**Issue by zeeoale** [aedoardo/telegram-twitch-sub-bot#1]
non è un vero e proprio ISSUE ma non essendo molto pratico con MongoDB (non l'ho mai usato in vita mia) quando tento di importare il json dell'esempio che hai inserito ricevo degli errori

`Uncaught:
SyntaxError: Missing semicolon. (2:8)
`
sbaglio qualcosa io? o c'è un errore nell'esempio che hai inserito tu?

**Comment by aedoardo** [comment]
Il JSON nel README è semplicemente un esempio di data che verrà inserito all'interno della collezione del database. Perciò, non è un vero e proprio dato che puoi inserire. Puoi provare comunque ad aggiungere la parentesi [ all'inizio e alla fine ] e vedere se ti carica quei dati, ma non ne sono sicuro.
